### ISSUE TITLE
Error compiling for ESP8266

### ISSUE THREAD

**Issue by fbalestrini** [mongoose-os-libs/modbus#1]
I would use the library on **ESP8266** boards but there are some errors compiling the source code of my demo project.

This is the most significant piece of my `mos.yml`:
```
config_schema:
  - ["modbus.enable", true]
conds:
  - when: mos.platform == "esp8266"
    apply:
      config_schema:
        - ["modbus.uart_no", 0]
        - ["modbus.tx_en_enable", false]
        - ["modbus.uart_tx_pin", 1]
        - ["modbus.uart_rx_pin", 3]
        - ["debug.stdout_uart", 1]
        - ["debug.stderr_uart", 1]
libs:
  - origin: https://github.com/mongoose-os-libs/modbus
``` 

These are some of the **compile errors**:
```console
deps/modbus/src/mgos_modbus.c:498:17: error: 'struct mgos_uart_dev_config' has no member named 'rx_gpio'
deps/modbus/src/mgos_modbus.c:501:17: error: 'struct mgos_uart_dev_config' has no member named 'tx_gpio'
deps/modbus/src/mgos_modbus.c:518:42: error: 'struct mgos_uart_dev_config' has no member named 'tx_gpio'
deps/modbus/src/mgos_modbus.c:517:56: error: 'struct mgos_uart_dev_config' has no member named 'rx_gpio'
deps/modbus/src/mgos_modbus.c:512:13: error: 'struct mgos_uart_dev_config' has no member named 'hd'
...
``` 

Looking forward for your support.
Many thanks in advance.
